# Generated by Django 5.0.6 on 2024-07-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_clothes_id_clothes_cloth_image_and_more'),
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='traders_fullname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='clothes.clothes'),
        ),
    ]
