# Generated by Django 5.0.6 on 2024-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_id', models.IntegerField()),
                ('cloth_name', models.CharField(verbose_name=40)),
                ('cloth_exporter', models.CharField(verbose_name=40)),
                ('cloth_material', models.CharField(verbose_name=40)),
                ('trending_date', models.DateField()),
            ],
        ),
    ]
