# Generated by Django 5.0.6 on 2024-07-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='id',
        ),
        migrations.AddField(
            model_name='clothes',
            name='cloth_image',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cloth_name',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
