# Generated by Django 5.0.6 on 2024-07-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter_id', models.IntegerField()),
                ('exporter_location', models.TextField()),
                ('exporter_name', models.CharField(max_length=20)),
            ],
        ),
    ]
