# Generated by Django 5.0.6 on 2024-07-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_clothes_id_clothes_cloth_image_and_more'),
        ('exporters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporter',
            name='exporter_cloth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exporters', to='clothes.clothes'),
        ),
    ]
